development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bingo_development
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bingo_test
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bingo_production
  pool: 5
  username: root
  password: root
  host: localhost
